# pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: first-netcore-app
  labels:
    app: kubedemo-aks
    component: netcore-app
spec:
  containers:
    - image: tsreg.azurecr.io/kubedemo:latest
      name: webapi
      ports:
        - containerPort: 80

